sonar.projectKey=job-application-manager-backend
sonar.projectName=Job Application Manager Backend
sonar.sources=app
sonar.tests=tests
sonar.python.version=3.11
sonar.python.coverage.reportPaths=coverage.xml
sonar.python.xunit.reportPath=test-results.xml
sonar.exclusions=**/__pycache__/**,**/*.pyc,app/static/**